### ISSUE TITLE
NameError: name 'printInteractiveHelp' is not defined

### ISSUE THREAD

**Issue by ghost** [ConceptJunkie/rpn#2]
After downloading rpn and launching it (I have runned `makeUnits.py`, `makeHelp.py` and `preparePrimeData.py`), this error happen when I try to print the help:

```
rpn 6.99.22 (7.0a22) - RPN command-line calculator
copyright (c) 2016 (1988), Rick Gutleber (rickg@his.com)

Type "help" for more information, and "exit" to exit.
rpn (1)>help
rpn help mode - 'topics' for a list of topics, 'exit' to return to rpn
rpn help>topics
Traceback (most recent call last):
  File "rpn.py", line 608, in <module>
    handleOutput( rpn( sys.argv[ 1 : ] ) )
  File "rpn.py", line 575, in rpn
    enterInteractiveMode( )
  File "rpn.py", line 261, in enterInteractiveMode
    enterHelpMode( terms[ 1 : ] )
  File "rpn.py", line 309, in enterHelpMode
    printInteractiveHelp( )
NameError: name 'printInteractiveHelp' is not defined
```

**Comment by ConceptJunkie** [comment]
This was caused by some changes I made yesterday.  I'm on vacation this week, :-), but I'll try to remember to fix it later today.
Rick
On Aug 3, 2016 03:29, Random Guy notifications@github.com wrote:After downloading rpn and launching it (I have runned makeUnits.py, makeHelp.py and preparePrimeData.py), this error happen when I try to print the help:

rpn 6.99.22 (7.0a22) - RPN command-line calculator
copyright (c) 2016 (1988), Rick Gutleber (rickg@his.com)

Type "help" for more information, and "exit" to exit.
rpn (1)>help
rpn help mode - 'topics' for a list of topics, 'exit' to return to rpn
rpn help>topics
Traceback (most recent call last):
  File "rpn.py", line 608, in <module>
    handleOutput( rpn( sys.argv[ 1 : ] ) )
  File "rpn.py", line 575, in rpn
    enterInteractiveMode( )
  File "rpn.py", line 261, in enterInteractiveMode
    enterHelpMode( terms[ 1 : ] )
  File "rpn.py", line 309, in enterHelpMode
    printInteractiveHelp( )
NameError: name 'printInteractiveHelp' is not defined

**Comment by ConceptJunkie** [comment]
Fixed.   I need to add interactive mode tests to the unit tests.   I rarely use it, so this bug has probably been around for a long time.
