### ISSUE TITLE
"Please run "makeUnits" to initialize the unit conversion data files"

### ISSUE THREAD

**Issue by dsanson** [ConceptJunkie/rpn#6]
Tried installing with pip. When I try to run the command, I get this error:

```
> rpn
Please run "makeUnits" to initialize the unit conversion data files.
```

Any advice?

**Comment by ConceptJunkie** [comment]
Hi.  Are you using 8.3?  I released that just a few days ago.  I tried installing it myself using virtualenv, and it worked for me.  The data files for the unit conversion stuff are bundled with the rpnChilada package, so I don't know why it can't find them.

I guess at this point, I'm not sure what the problem can be.  Can you give me specifics for your installation (i.e., what platform, what version of Python, etc.)

In the meantime, I'll try to figure out what the problem might be and see if there's a workaround.  I never made executables for makeUnits, etc., because there's no reason why an end-user would need to run them.  Maybe it's time to change that.

Thanks,

Rick

----- Original Message -----

**Comment by dsanson** [comment]
Sorry! I should have given you more details. I am on a Mac, OSX 10.15.4, running Python 3.7. pip tells me it installed version 8.3.0.

I've made some progress. I copied your makeUnits.py script from the repository (not the one in `rpn/`, the one in the root directory, and ran it. Then, when I tried running rpn, I was told that I needed to run "makeHelp" to initialize the help files. So now I am doing that. It seems to be taking a long time generating example 1248. I'll let you know when I make more progress.

**Comment by ConceptJunkie** [comment]
Yeah, I've never tested on a Mac, although I will actually be able to in a few weeks.

I was planning to cut a new release with makeUnits and makeHelp added to scripts/.   makeHelp is quite slow because a few of the examples it runs do some serious calculations, although it shouldn't take more than a few minutes.

Thanks for getting back to me.  When I get access to a Mac, hopefully I can figure out why the wheel doesn't work for installing the data. 

Once you get it working, try testRPN, and let me know if it passes all the unit tests.   That one also takes several minutes.

Rick

----- Original Message -----

**Comment by dsanson** [comment]
Just reporting back that I never could get it to generate example 1248. Left it for a few hours at least, churning away (on a recent MacBook Pro).

**Comment by ConceptJunkie** [comment]
OK, this is related to the other problem.  rpn can't find the help data files, which is why it wants you to build the help in the first place.  Apparently, it also can't find the prime number data cache, so it's computing the millionth prime the hard way. 

Generating help takes 92 seconds on my ancient laptop. 

If I can solve the first problem, then all the other problems will go away.

Rick

----- Original Message -----

**Comment by ConceptJunkie** [comment]
David:

I've pushed an update to rpn that should fix your problem.   I hope.

Can you update the wheel to version 8.3.1 and let me know if that helps?

Thanks,

Rick

----- Original Message -----

**Comment by dsanson** [comment]
Yes, it works! Thanks!

**Comment by ConceptJunkie** [comment]
Awesome!  Thank you so much.
